# Generated by Django 3.1.3 on 2020-11-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='blogimages/')),
                ('author', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
