# Generated by Django 3.1.3 on 2020-12-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='visitor',
            new_name='user2',
        ),
    ]
