# Generated by Django 3.1.3 on 2020-12-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
