# Generated by Django 3.1.3 on 2021-05-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='#', max_length=500)),
                ('img', models.ImageField(default='#', upload_to='media/')),
                ('price', models.CharField(default='#', max_length=40)),
                ('desc', models.TextField(default='#')),
                ('slug', models.SlugField(default='', max_length=130)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
