# Generated by Django 3.1.3 on 2021-05-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210503_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
