# Generated by Django 3.1.3 on 2021-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmonial',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media/')),
                ('desc', models.TextField(default='#')),
            ],
        ),
    ]
